### ISSUE TITLE
Implement "uses-this" feature

### ISSUE THREAD

**Issue by HalfAnAvocado** [HalfAnAvocado/ssg#3]
- Store software I use in a special YAML file `uses-this.yaml`
- Using that file as input generate a HTML page listing the software I use
- For each entry in the YAML input:
  - Generate a HTML description list `dl`, where:
  - The _description term_ `dt` is the name of the **software category (e.g. Operating System, Text editor, Web browser)**
  - The _description details_ `dd` is a **list of links** `a` of the software that I use, where:
    -  The link text is the **name of the software**
    - The link `href` attribute is the **link to the software's official website**

# Example YAML input
```yaml
- title: Core
  categories:
  - title: Operating system
    software:
    -  name: Manjaro
       link: https://manjaro.org/
    -  name: Android
       link: https://www.android.com/
  - title: Init system
    software:
    -  name: systemd
       link: https://systemd.io/
    -  name: runit
       link: https://smarden.org/runit/
```

# Example HTML output
```html
<section>
  <h2>Core</h2>
    <dl>
      <dt>Operating system</dt>
      <dd><a href="https://manjaro.org/">Manjaro</a>, <a href="https://www.android.com/">Android</a></dd>
      <dt>Init system</dt>
      <dd><a href="https://systemd.io/">systemd</a>, <a href="https://smarden.org/runit/">runit</a></dd>
    </dl>
</section>
```
